name: Deploy

on:
  workflow_call:
    inputs:
      environment:
        description: Repository environment
        type: string
        required: true
      tag:
        description: Technically it can be tag or branch
        type: string
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    permissions:
      id-token: write
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
          token: ${{ secrets.HFT_GITHUB_SUBMODULES_ACCESS_TOKEN }}
      - uses: kindkitchen/genv@v1.0.0
        with:
          vars_obj: ${{ toJson(vars) }}
          secrets_obj: ${{ toJson(secrets) }}
          dotenv_content: |
            TAG: ${{ inputs.tag }}
      - name: Create new branch to flat submodules into one deployable repository
        run: |
          git config --global user.email "hft@ci.cd"
          git config --global user.name "Hft Root"
          git checkout -b main_dist
          git submodule foreach --recursive \
            'git rm --cached ../$name -r; rm -rf ../.git/modules/$name'
          git add .
          git commit -m "$(git log -1 --pretty=%B main)"
          git push origin main_dist --force
