name: ðŸš€ Click to produce deployable artifact!

on:
  workflow_dispatch:
    inputs:
      gh_environment:
        type: environment
        description: Repository environment

jobs:
  call_deploy:
    permissions:
      id-token: write
      contents: write
    uses: ./.github/workflows/produce_deployable_artifact.yml
    with:
      environment: ${{ inputs.gh_environment }}
      tag: ${{ github.ref_name }}
    secrets: inherit
