#############################################################################
### This action flat all code from all submodules into single codebase and
### push it into private repository. This will allow in easy way to manage
### codebase in later ci/cd flows (especially in deployments).
#############################################################################
name: Produce deployable artifact

on:
  workflow_call:
    inputs:
      environment:
        description: Repository environment
        type: string
        required: true
      tag:
        description: Technically it can be tag or branch
        type: string
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    permissions:
      id-token: write
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
          token: ${{ secrets.HFT_GITHUB_SUBMODULES_ACCESS_TOKEN }}
      - uses: kindkitchen/genv@v1.0.0
        with:
          vars_obj: ${{ toJson(vars) }}
          secrets_obj: ${{ toJson(secrets) }}
          dotenv_content: |
            TAG: ${{ inputs.tag }}
      - name: Create git user
        run: |
          git config --global user.email "hft@ci.cd"
          git config --global user.name "Hft Root"

      - name: Flat submodules into one codebase
        run: bash ./.github/script/detach_submodules.sh

      - uses: extractions/setup-just@v3
      - name: Update links with physical files
        run: |
          just make_libs_real_in_app hft_web

      - name: Update 'dist' repositories
        run: bash ./.github/script/update_dist_repos.sh
