name: PR completed produce deployable artifact!

on:
  pull_request:
    branches: [main]
    types:
      - closed

jobs:
  call_deploy:
    permissions:
      id-token: write
      contents: write
    uses: ./.github/workflows/produce_deployable_artifact.yml
    with:
      environment: production
      tag: ${{ github.ref_name }}
    secrets: inherit
